#!/bin/bash

# Get the name of the new branch
branch_name=$1

# Create the new branch and switch to it
git checkout -b $branch_name

# Set the upstream branch to the remote repository
git push --set-upstream origin $branch_name


